[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 环境变量（在Netlify后台设置）
[build.environment]
  CLOUDINARY_CLOUD_NAME = "your-cloud-name"
  CLOUDINARY_API_KEY = "your-api-key"
  CLOUDINARY_API_SECRET = "your-api-secret"
  JWT_SECRET = "your-jwt-secret"
